### PR TITLE
fix: user group of the azure devops user for Linux and Darwin

### PR DESCRIPTION
**Pull request by askalski85**
Fixes: https://github.com/gsoft-inc/ansible-role-azure-devops-agent/issues/48

### CODE REVIEW

**Comment by askalski85** [comment]
Hi @yohanb @rockdreamer could you please take a look?

Fyi @mjiderhamn.

**Comment by yohanb** [comment]
LGTM!  I'll release it today on galaxy.

**Comment by rockdreamer** [comment]
Neat! Thank you for taking the time to improve it!

**Comment by yohanb** [comment]
done!
image

**Pull request merged**
